hello-node-service:
  build: .
  links:
    - 'redis:redis'
  ports:
    - '6900:7890'
  volumes:
    - ./config:/pn-minions/config
    - ./lib:/pn-minions/lib
    - ./script:/pn-minions/script
    - ./_tmp:/pn-minions/_tmp
